name: kl
description: Basic directive for layout
version: 0.0.1

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  http: ^0.11.3+13
  meta: ^1.0.5

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular2
#web:
#  compiler:
#    debug: dartdevc