name: kl
description: Basic directive for layout
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.45.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+9
  meta: ^1.0.5
  rxdart: ^0.16.0

dev_dependencies:
#  angular_test: ^1.0.0
  test: ^0.12.21
