name: kl
description: Basic directive for layout in angular dart
version: 1.0.0
author: Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Kleak/kl

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  meta: ^1.0.5
  rxdart: '>=0.16.0 <1.0.0'

dev_dependencies:
#  angular_test: ^1.0.0
  test: ^1.3.0
